const pulseAnimation = {
  animation: "pulse 1.5s infinite",
  boxShadow: "0 0 15px 5px rgba(245, 166, 35, 0.5)",
};

export const getStyles = (theme, fontSize, isOpen, isListening) => ({
  /* ── Shloka translation ────────────────────────────────── */
  shlokaTranslation: {
    fontSize: fontSize === "small" ? "0.9rem" : fontSize === "medium" ? "1rem" : "1.15rem",
    color: "var(--gold-bright)",
    lineHeight: "1.7",
    marginTop: "0.8rem",
    marginBottom: "0.6rem",
    fontStyle: "italic",
    borderTop: "1px solid var(--border-soft)",
    paddingTop: "0.8rem",
  },

  /* ── Scroll-to-top ─────────────────────────────────────── */
  scrollToTopStyle: {
    position: "fixed",
    right: "20px",
    backgroundColor: "var(--bg-elevated)",
    border: "1px solid var(--border-soft)",
    padding: "0",
    borderRadius: "999px",
    cursor: "pointer",
    fontSize: "0.95rem",
    fontWeight: "600",
    boxShadow: "var(--shadow-lg)",
    transition: "all 0.25s ease-in-out",
    letterSpacing: "0.5px",
    zIndex: 1000,
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  upstyle: {
    width: "40px",
    height: "40px",
    color: "var(--gold)",
  },

  /* ── Utility buttons ───────────────────────────────────── */
  smallButtonStyle: {
    padding: "0.55rem 1.1rem",
    fontSize: "0.88rem",
    backgroundColor: "rgba(245, 200, 120, 0.1)",
    color: "var(--gold-bright)",
    border: "1px solid var(--border-soft)",
    borderRadius: "var(--r-md)",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    cursor: "pointer",
    fontWeight: 600,
    fontFamily: "var(--font-body)",
    letterSpacing: "0.4px",
    boxShadow: "none",
    transition: "all 0.3s ease",
  },

  favoritesButton: {
    padding: "0.55rem 1.1rem",
    fontSize: "0.88rem",
    backgroundColor: "rgba(245, 200, 120, 0.1)",
    color: "var(--gold-bright)",
    border: "1px solid var(--border-soft)",
    borderRadius: "var(--r-md)",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    cursor: "pointer",
    fontWeight: 600,
    fontFamily: "var(--font-body)",
    letterSpacing: "0.4px",
    transition: "all 0.3s ease",
  },

  selectedChatBubble: {
    borderLeft: "4px solid var(--gold)",
    backgroundColor: "rgba(245, 200, 120, 0.06)",
    boxShadow: "var(--shadow-md)",
  },

  checkboxContainer: {
    position: "absolute",
    top: "12px",
    left: "12px",
    zIndex: 5,
  },

  checkbox: {
    width: "18px",
    height: "18px",
    cursor: "pointer",
    accentColor: "var(--gold)",
  },

  /* ── Edit controls ─────────────────────────────────────── */
  editButton: {
    position: "absolute",
    top: "12px",
    right: "68px",
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
    color: "var(--gold-bright)",
    fontSize: "1.1rem",
    padding: "8px",
    transition: "all 0.2s ease",
    opacity: "0.7",
    zIndex: 10,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "36px",
    height: "36px",
  },

  editForm: {
    marginTop: "0.8rem",
    marginBottom: "1rem",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    width: "100%",
  },

  editInput: {
    width: "100%",
    padding: "0.7rem",
    borderRadius: "var(--r-md)",
    border: "1px solid var(--border-soft)",
    fontSize: fontSize === "small" ? "0.9rem" : fontSize === "medium" ? "1rem" : "1.1rem",
    backgroundColor: "var(--bg-primary)",
    color: "var(--text-primary)",
    boxShadow: "none",
    transition: "all 0.3s ease",
    outline: "none",
    fontFamily: "var(--font-body)",
  },

  editButtonsContainer: {
    display: "flex",
    gap: "10px",
    justifyContent: "flex-end",
    marginTop: "8px",
  },

  editSaveButton: {
    backgroundColor: "var(--success)",
    color: "#fff",
    border: "none",
    padding: "0.6rem 1.2rem",
    borderRadius: "var(--r-md)",
    cursor: "pointer",
    fontSize: "0.9rem",
    fontWeight: "500",
    boxShadow: "var(--shadow-sm)",
    transition: "all 0.2s ease",
    letterSpacing: "0.3px",
    minWidth: "60px",
  },

  editCancelButton: {
    backgroundColor: "var(--error)",
    color: "#fff",
    border: "none",
    padding: "0.6rem 1.2rem",
    borderRadius: "var(--r-md)",
    cursor: "pointer",
    fontSize: "0.9rem",
    fontWeight: "500",
    boxShadow: "var(--shadow-sm)",
    transition: "all 0.2s ease",
    letterSpacing: "0.3px",
    minWidth: "60px",
  },

  /* ── Gita quote banner ─────────────────────────────────── */
  geetaQuote: {
    fontSize: fontSize === "small" ? "1.1rem" : fontSize === "medium" ? "1.2rem" : "1.3rem",
    color: "var(--gold-bright)",
    fontWeight: "bold",
    margin: "1.5rem 0",
    background: "var(--grad-glass)",
    padding: "18px",
    borderRadius: "var(--r-lg)",
    boxShadow: "var(--shadow-md)",
    borderLeft: "4px solid var(--gold)",
    lineHeight: "1.6",
    letterSpacing: "0.2px",
  },

  /* ── Language toggle ───────────────────────────────────── */
  languageToggle: {
    display: "flex",
    justifyContent: "center",
    marginTop: "1rem",
    marginBottom: "1rem",
    gap: "8px",
    flexWrap: "wrap",
  },

  languageButton: {
    backgroundColor: "transparent",
    color: "var(--text-primary)",
    border: "1.5px solid var(--border-strong)",
    padding: "0.5rem 1.1rem",
    borderRadius: "var(--r-full)",
    cursor: "pointer",
    fontSize: fontSize === "small" ? "0.85rem" : fontSize === "medium" ? "0.9rem" : "1rem",
    fontWeight: "600",
    boxShadow: "none",
    transition: "all 0.2s ease",
    letterSpacing: "0.3px",
    minWidth: "60px",
    fontFamily: "var(--font-body)",
  },

  favoritesSection: {
    marginTop: "2rem",
    borderTop: "1px solid var(--border-soft)",
    paddingTop: "1.5rem",
  },

  /* ── Form / input ──────────────────────────────────────── */
  form: {
    marginBottom: "2rem",
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    width: "100%",
    boxSizing: "border-box",
    padding: "0 1rem",
  },

  floatingLabel: {
    position: "absolute",
    left: "2.8rem",
    top: "50%",
    transform: "translateY(-50%)",
    color: "var(--text-muted)",
    fontSize: "1rem",
    pointerEvents: "none",
    transition: "all 0.2s ease-out",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: "calc(100% - 3rem)",
  },
  floatingLabelActive: {
    top: "0.3rem",
    fontSize: "0.75rem",
    color: "var(--gold)",
    transform: "translateY(0)",
    whiteSpace: "normal",
  },
  floatingPlaceholder: {
    animation: "scrollText 10s linear infinite",
    whiteSpace: "nowrap",
    display: "inline-block",
  },
  inputContainer: {
    position: "relative",
    width: "100%",
    boxSizing: "border-box",
  },
  inputWrapper: {
    position: "relative",
    width: "100%",
    boxSizing: "border-box",
    overflow: "hidden",
  },
  inputWrap: {
    position: "relative",
    width: "80%",
    boxSizing: "border-box",
    overflow: "hidden",
    gap: "8px",
    display: "flex",
  },

  scrollingPlaceholder: {
    position: "absolute",
    top: "50%",
    left: "2.8rem",
    transform: "translateY(-50%)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    pointerEvents: "none",
    right: "0.7rem",
  },
  scrollingPlaceholder2: {
    position: "absolute",
    top: "50%",
    left: "2.8rem",
    right: "4rem",
    transform: "translateY(-50%)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    pointerEvents: "none",
  },
  scrollingText: {
    display: "inline-block",
    paddingLeft: "100%",
    animation: "scrollText 12s linear infinite",
    color: "var(--gold-bright)",
    fontSize: "1rem",
    fontFamily: "var(--font-display)",
    opacity: 0.85,
  },

  input: {
    width: "100%",
    padding: "0.85rem 1rem 0.85rem 2.8rem",
    fontSize: "1rem",
    borderRadius: "var(--r-md)",
    border: "1px solid var(--border-soft)",
    outline: "none",
    backgroundColor: "var(--bg-primary)",
    color: "var(--text-primary)",
    boxSizing: "border-box",
    flexGrow: 1,
    fontFamily: "var(--font-body)",
    transition: "border-color 0.2s ease, box-shadow 0.2s ease",
  },

  bookIcon: {
    position: "absolute",
    top: "50%",
    left: "1rem",
    transform: "translateY(-50%)",
    fontSize: "1.3rem",
    color: isListening ? "var(--error)" : "var(--gold)",
    pointerEvents: "none",
    zIndex: 1,
  },

  /* ── Submit buttons ────────────────────────────────────── */
  submitButton: {
    backgroundColor: "var(--gold)",
    color: "#1a0f00",
    border: "none",
    padding: "0.6rem 4rem",
    borderRadius: "var(--r-full)",
    cursor: "pointer",
    fontSize: fontSize === "small" ? "1rem" : fontSize === "medium" ? "1.05rem" : "1.15rem",
    fontWeight: "bold",
    boxShadow: "var(--shadow-md), var(--glow-gold)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    transition: "all 0.3s ease",
    letterSpacing: "0.4px",
    fontFamily: "var(--font-body)",
  },

  smallSubmit: {
    backgroundColor: "var(--gold)",
    color: "#1a0f00",
    border: "none",
    padding: "0.4rem 1rem",
    borderRadius: "var(--r-md)",
    cursor: "pointer",
    fontSize: fontSize === "small" ? "0.9rem" : fontSize === "medium" ? "1rem" : "1.1rem",
    fontWeight: "bold",
    boxShadow: "var(--shadow-sm), var(--glow-gold)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    transition: "all 0.3s ease",
    letterSpacing: "0.2px",
  },

  voiceButton: {
    backgroundColor: isListening ? "var(--error)" : "var(--gold)",
    color: isListening ? "#fff" : "#1a0f00",
    border: "none",
    padding: "0.8rem",
    borderRadius: "var(--r-md)",
    cursor: "pointer",
    fontSize: "1rem",
    transition: "all 0.3s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "44px",
    height: "44px",
    transform: isListening ? "scale(1.1)" : "scale(1)",
    boxShadow: isListening
      ? "0 0 15px 5px rgba(239, 108, 108, 0.5)"
      : "var(--shadow-sm), var(--glow-gold)",
    ...(isListening ? pulseAnimation : {}),
  },

  /* ── Sidebar ───────────────────────────────────────────── */
  sidebar: {
    position: "fixed",
    left: isOpen ? "0" : "-300px",
    top: "0",
    height: "100vh",
    width: "300px",
    backgroundColor: "var(--bg-primary)",
    borderRight: "1px solid var(--border-soft)",
    boxShadow: "var(--shadow-xl)",
    transition: "left 0.3s ease",
    zIndex: 1000,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    backdropFilter: "blur(24px) saturate(140%)",
  },
  opensidebarbutton: {
    position: "fixed",
    left: "16px",
    top: "16px",
    width: "44px",
    height: "44px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0",
    background: "var(--grad-glass)",
    backdropFilter: "blur(20px) saturate(140%)",
    WebkitBackdropFilter: "blur(20px) saturate(140%)",
    color: "var(--gold-bright)",
    border: "1px solid var(--border-strong)",
    borderRadius: "var(--r-full)",
    cursor: "pointer",
    zIndex: 900,
    fontSize: "1.15rem",
    fontWeight: "500",
    boxShadow: "var(--shadow-md), var(--glow-gold)",
    fontFamily: "var(--font-body)",
    transition: "all 0.2s var(--ease-out)",
  },
  logoutbutton: {
    position: "fixed",
    right: "16px",
    top: "16px",
    width: "44px",
    height: "44px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0",
    background: "var(--grad-glass)",
    backdropFilter: "blur(20px) saturate(140%)",
    WebkitBackdropFilter: "blur(20px) saturate(140%)",
    color: "var(--gold-bright)",
    border: "1px solid var(--border-strong)",
    borderRadius: "var(--r-full)",
    cursor: "pointer",
    fontSize: "1.05rem",
    fontWeight: "500",
    boxShadow: "var(--shadow-md), var(--glow-gold)",
    zIndex: 900,
    fontFamily: "var(--font-body)",
    transition: "all 0.2s var(--ease-out)",
  },
  Set: {
    background: "var(--grad-gold)",
    color: "#1a0f00",
    border: "none",
    padding: "8px 15px",
    borderRadius: "var(--r-md)",
    cursor: "pointer",
    fontSize: "0.9rem",
    fontWeight: "600",
  },

  /* ── Chat area ─────────────────────────────────────────── */
  chatContainer: {
    marginTop: "2rem",
    width: "100%",
  },

  deleteButton: {
    position: "absolute",
    top: "12px",
    right: "12px",
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
    color: "var(--error)",
    fontSize: "1.1rem",
    padding: "8px",
    transition: "all 0.2s ease",
    opacity: "0.7",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "36px",
    height: "36px",
  },

  userMessage: {
    color: "var(--success)",
    fontWeight: "600",
    marginBottom: "0.8rem",
    fontSize: fontSize === "small" ? "0.95rem" : fontSize === "medium" ? "1.05rem" : "1.15rem",
    letterSpacing: "0.2px",
    lineHeight: "1.6",
  },

  timestamp: {
    fontSize: fontSize === "small" ? "0.75rem" : fontSize === "medium" ? "0.8rem" : "0.85rem",
    color: "var(--text-muted)",
    marginBottom: "0.8rem",
    fontStyle: "italic",
    opacity: "0.9",
  },

  botResponse: {
    color: "var(--text-body)",
    marginBottom: "1rem",
    lineHeight: "1.7",
    fontSize: fontSize === "small" ? "0.95rem" : fontSize === "medium" ? "1.05rem" : "1.15rem",
    letterSpacing: "0.2px",
  },

  shlokaContainer: {
    background: "var(--grad-glass)",
    border: "1px solid var(--border-soft)",
    borderLeft: "3px solid var(--gold)",
    borderRadius: "var(--r-lg)",
    padding: "1.2rem 1.4rem",
    marginTop: "1.2rem",
    textAlign: "center",
    fontWeight: "600",
    boxShadow: "var(--shadow-sm)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
  },

  shloka: {
    fontSize: fontSize === "small" ? "1rem" : fontSize === "medium" ? "1.1rem" : "1.2rem",
    color: "var(--gold-bright)",
    lineHeight: "1.7",
    letterSpacing: "0.2px",
    fontFamily: "var(--font-display)",
  },

  /* ── Preferences bar ───────────────────────────────────── */
  preferencesBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "1.5rem",
    padding: "0.8rem",
    backgroundColor: "rgba(245, 200, 120, 0.04)",
    borderRadius: "var(--r-lg)",
    border: "1px solid var(--border-soft)",
    boxShadow: "none",
    flexWrap: "wrap",
    gap: "8px",
  },

  preferencesButton: {
    backgroundColor: "transparent",
    color: "var(--gold-bright)",
    border: "none",
    padding: "0.6rem",
    borderRadius: "var(--r-md)",
    cursor: "pointer",
    fontSize: "1.1rem",
    display: "flex",
    alignItems: "center",
    transition: "all 0.2s ease",
    boxShadow: "none",
    opacity: "0.85",
    minWidth: "36px",
    minHeight: "36px",
  },

  fontSizeControls: {
    display: "flex",
    gap: "6px",
  },

  fontButton: {
    backgroundColor: "rgba(245, 200, 120, 0.12)",
    color: "var(--text-primary)",
    border: "1px solid var(--border-soft)",
    padding: "0.45rem 0.6rem",
    borderRadius: "var(--r-md)",
    cursor: "pointer",
    transition: "all 0.2s ease",
    fontWeight: "600",
    opacity: "0.9",
    minWidth: "32px",
    minHeight: "32px",
  },

  favoriteButton: {
    position: "absolute",
    top: "12px",
    right: "40px",
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
    fontSize: "1.1rem",
    padding: "8px",
    transition: "all 0.2s ease",
    opacity: "0.8",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "36px",
    height: "36px",
  },

  spinner: {
    animation: "spin 1.8s ease-in-out infinite",
  },

  buttonContainer: {
    display: "flex",
    justifyContent: "center",
    gap: "10px",
    flexWrap: "wrap",
  },
  favend: {
    position: "absolute",
    top: "-0.8rem",
    left: "50%",
    transform: "translateX(-50%)",
    backgroundColor: "var(--bg-primary)",
    padding: "0 1rem",
    color: "var(--text-muted)",
    fontStyle: "italic",
    fontFamily: "var(--font-display)",
    fontSize: "0.9rem",
  },
  selected: {
    backgroundColor: "rgba(245, 200, 120, 0.12)",
    color: "var(--gold-bright)",
    padding: "5px 10px",
    borderRadius: "var(--r-full)",
    fontSize: "0.8rem",
    fontWeight: "bold",
    border: "1px solid var(--border-soft)",
  },

  chatBubble: {
    backgroundColor: "var(--bg-elevated)",
    padding: "1.5rem",
    borderRadius: "var(--r-lg)",
    marginBottom: "1.2rem",
    boxShadow: "var(--shadow-sm)",
    textAlign: "left",
    position: "relative",
    borderLeft: "3px solid var(--gold)",
    transition: "all 0.3s ease",
    border: "1px solid var(--border-subtle)",
  },

  verseInfo: {
    fontSize: fontSize === "small" ? "0.9rem" : fontSize === "medium" ? "1rem" : "1.1rem",
    color: "var(--text-secondary)",
    marginTop: "0.6rem",
    fontStyle: "italic",
    fontFamily: "var(--font-display)",
    letterSpacing: "0.2px",
    opacity: "0.9",
  },

  shareButton: {
    background: "var(--grad-gold)",
    color: "#1a0f00",
    border: "1px solid rgba(255, 220, 150, 0.4)",
    padding: "0.6rem 1.25rem",
    borderRadius: "var(--r-full)",
    cursor: "pointer",
    fontSize: fontSize === "small" ? "0.88rem" : fontSize === "medium" ? "0.92rem" : "1rem",
    marginTop: "1rem",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    boxShadow: "var(--shadow-sm), var(--glow-gold)",
    transition: "all 0.2s ease",
    fontWeight: "600",
    letterSpacing: "0.3px",
    minWidth: "80px",
    fontFamily: "var(--font-body)",
  },

  /* ── Skeleton loading ──────────────────────────────────── */
  skeletonChatBubble: {
    backgroundColor: "var(--bg-elevated)",
    padding: "1.5rem",
    borderRadius: "var(--r-lg)",
    marginBottom: "1.2rem",
    border: "1px solid var(--border-subtle)",
    animation: "shimmer 2s ease-in-out infinite",
  },
  skeletonText: {
    height: "14px",
    background: "linear-gradient(90deg, var(--border-subtle) 25%, rgba(245,200,120,0.08) 50%, var(--border-subtle) 75%)",
    backgroundSize: "200% 100%",
    animation: "shimmer 2s ease-in-out infinite",
    borderRadius: "6px",
    marginBottom: "10px",
  },
  skeletonShortText: {
    height: "14px",
    width: "60%",
    background: "linear-gradient(90deg, var(--border-subtle) 25%, rgba(245,200,120,0.08) 50%, var(--border-subtle) 75%)",
    backgroundSize: "200% 100%",
    animation: "shimmer 2s ease-in-out infinite",
    borderRadius: "6px",
    marginBottom: "10px",
  },
});
